trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
    displayName: 'Set up Python'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements-dev.txt
    displayName: 'Install dependencies'

  - script: |
      pytest --cov=app --cov-report=term-missing --cov-fail-under=70
    displayName: 'Run tests with coverage (fail under 70%)'

  - script: |
      python -m py_compile $(git ls-files '*.py')
    displayName: 'Build sanity check'