"""remove species, breed, birthday from Pet

Revision ID: 6eed6dd81759
Revises: d02df364d225
Create Date: 2025-10-02 17:36:43.484723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eed6dd81759'
down_revision = 'd02df364d225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('species')
        batch_op.drop_column('breed')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('species', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
